--- NoMethodError.new(error_message[, name[, args]])  ruby 1.8 feature

    例外オブジェクトを生成して返します。
    argsは、メソッド呼び出しに使われた引数です。


        nom = NoMethodError.new("message", "foo", [1,2,3])
        p nom.name
        p nom.args

        # => "foo"
             [1, 2, 3]

